global:
  imagePullPolicy: Always

metrics:
  enable: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: qcloud

nginx-ingress-controller:
  enabled: false

tca:
  podAntiAffinity:
    enable: true

  commonConfig:
    publicUrl: "xxx"

  web:
    image:
      repository: wrype/tca-web
      tag: 97cd34581f
    service:
      type: NodePort

  main:
    image:
      repository: wrype/tca-main
      tag: 4bcc29a1d2
    server:
      service:
        type: NodePort

  analysis:
    image:
      repository: wrype/tca-analysis
      tag: 4bcc29a1d2
    server:
      service:
        type: NodePort

  login:
    image:
      repository: wrype/tca-login
      tag: 4bcc29a1d2
    server:
      service:
        type: NodePort

  file:
    image:
      repository: wrype/tca-file
      tag: 4bcc29a1d2
    server:
      service:
        type: NodePort
    settings:
      storageClient: "cos"
      tencentcos:
        enabled: "true"
        appId: "xxx"
        secretId: "xxx"
        secretKey: "xxx"
        region: "xxx"
        rootBucket: "xxx"

  scmproxy:
    image:
      repository: wrype/tca-scmproxy
      tag: 4bcc29a1d2
    service:
      type: NodePort

  client:
    image:
      repository: wrype/tca-client
      tag: 4bcc29a1d2

  gateway:
    service:
      type: NodePort
